heat_template_version: 2013-05-23

parameters:

  image:
    type: string
  flavor:
    type: string
  key_name:
    type: string
  external_network_id:
    type: string
  allocation_pool:
    type: json

resources:
  secgroup_all_open:
    type: "OS::Neutron::SecurityGroup"
    properties:
      rules:
        - protocol: icmp
        - protocol: tcp
        - protocol: udp

  fixed_network:
    type: "OS::Neutron::Net"

  fixed_subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: 10.1.0.0/24
      network_id: {get_resource: fixed_network}
      allocation_pools:
        - {get_param: allocation_pool}


  router:
    type: "OS::Neutron::Router"
    properties:
      external_gateway_info:
        network: {get_param: external_network_id}

  router_port:
    type: "OS::Neutron::RouterInterface"
    properties:
      router_id: {get_resource: router}
      subnet_id: {get_resource: fixed_subnet}

  server:
    type: "OS::Nova::Server"
    properties:
      image:
        get_param: image
      flavor:
        get_param: flavor
      key_name:
        get_param: key_name
      networks:
        - port: {get_resource: server_eth0}

  server_eth0:
    type: "OS::Neutron::Port"
    properties:
      network_id: {get_resource: fixed_network}
      fixed_ips:
        - subnet_id: {get_resource: fixed_subnet}
      security_groups:
        - {get_resource: secgroup_all_open}

  server_floating:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network_id: {get_param: external_network_id}
      port_id: {get_resource: server_eth0}

outputs:

  server_ip:
    value: {get_attr: [server_floating, floating_ip_address]}

